language: node_js
node_js:
  - "6"
  - "node"
sudo: false
script:
  - "npm run-script test-travis"
after_script:
  - "test -e ./coverage/lcov.info && npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
